export const
  AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR',
  AUTHENTICATED_USER = 'AUTHENTICATED_USER',
  FORGOT_PASSWORD_REQUEST = 'forgot_password_request',
  PROTECTED_TEST = 'protected_test',
  RESET_PASSWORD_REQUEST = 'reset_password_request',
  UNAUTHENTICATED_USER = 'unAUTHENTICATED_USER';
