import About from './about/About';
import Contact from './contact/Contact';
import Donate from './donate/Donate';
import Home from './home/Home';
import Layout from 'layout/Layout';
import LayoutFull from 'layout/LayoutFull';
import Login from './login/Login';
import NotFound from './notFound/NotFound';
import Projects from './projects/Projects';
import Register from './register/Register';
import Team from './team/Team';

exports.About = About;
exports.Contact = Contact;
exports.Donate = Donate;
exports.Home = Home;
exports.Layout = Layout;
exports.LayoutFull = LayoutFull;
exports.Login = Login;
exports.NotFound = NotFound;
exports.Projects = Projects;
exports.Register = Register;
exports.Team = Team;